variables:
  PLUGIN_NAME: 'authorVersion'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ops_plugins_unit_tests_model.yml'