variables:
  PLUGIN_NAME: 'authorVersion'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_3_0
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ops/cypress_tests.yml'